# Generated by Django 4.2.6 on 2025-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_staticpages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Industry Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("image", models.ImageField(upload_to="")),
                ("status", models.BooleanField(default=True)),
                ("show_home", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Industry",
            },
        ),
    ]
