# Generated by Django 4.2.6 on 2025-06-04 06:25

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_industry_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="image",
            field=models.FileField(
                upload_to="", validators=[website.validators.validate_file_extension]
            ),
        ),
    ]
