# Generated by Django 4.2.6 on 2025-06-04 07:11

from django.db import migrations, models
import django.db.models.deletion
import website.validators


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_industry_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name_plural": "Industries"},
        ),
        migrations.AlterModelOptions(
            name="staticpages",
            options={"ordering": ("id",), "verbose_name_plural": "Static Pages"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "Users"},
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Template Name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="",
                        validators=[website.validators.validate_file_extension],
                    ),
                ),
                ("short_description", models.TextField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[("free", "Free"), ("premium", "Premium")],
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.industry",
                    ),
                ),
            ],
        ),
    ]
