# Generated by Django 4.2.6 on 2025-06-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_industry_options_alter_staticpages_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="SubCategory Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry",
                        to="website.industry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub Industries",
            },
        ),
        migrations.AddField(
            model_name="template",
            name="sub_industry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.subindustry",
            ),
            preserve_default=False,
        ),
    ]
