# Generated by Django 4.2.6 on 2025-06-04 11:28

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_subindustry_template_sub_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="details_image",
            field=models.ImageField(
                blank=True,
                upload_to="",
                validators=[website.validators.validate_file_extension],
            ),
        ),
    ]
