# Generated by Django 4.2.6 on 2025-06-06 11:23

from django.db import migrations, models
import django.utils.timezone
import website.validators


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_template_details_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="upload_file",
            field=models.FileField(
                default=django.utils.timezone.now,
                upload_to="upload",
                validators=[website.validators.validate_file_extension_zip],
            ),
            preserve_default=False,
        ),
    ]
