# Generated by Django 4.2.6 on 2025-06-06 14:16

import ckeditor_uploader.fields
from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_template_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="template_details",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="upload_file",
            field=models.FileField(
                upload_to="upload_html_files/",
                validators=[website.validators.validate_file_extension_zip],
                verbose_name="upload html/zip file",
            ),
        ),
    ]
