# Generated by Django 4.2.6 on 2025-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_template_template_details_alter_template_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="browsers",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="file_include",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="html_type",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="item_code",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="last_update",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="releadse_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="theme_version",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
