# Generated by Django 4.2.6 on 2025-06-07 02:13

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_template_browsers_template_file_include_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="details_image",
            field=models.ImageField(
                blank=True,
                default="website.jpg",
                upload_to="",
                validators=[website.validators.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="releadse_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
