# Generated by Django 4.2.6 on 2025-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="template_id_str",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
