# Generated by Django 4.2.6 on 2025-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_download_template_id_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
