# Generated by Django 4.2.6 on 2026-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_template_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="preview_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
