# Generated by Django 4.2.6 on 2026-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_template_preview_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="preview_link",
            field=models.CharField(blank=True, default="#", max_length=200, null=True),
        ),
    ]
