# Generated by Django 4.2.6 on 2026-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_template_preview_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="downloads",
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
